[package]
name = "plang"
version = "0.1.0"
edition = "2021"
authors = [ "Eduardo Leegwater Simões <eduardols@protonmail.com>" ]

[dependencies]
dusk-plonk = "0.9.0-rc.0"
pest = "2.1.3"
pest_derive = "2.1.0"

[dev-dependencies]
rand_core = "0.6.3"
